# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wizcard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wizcard

  pod 'CountryPickerSwift', '1.4.5'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'LinkedinSwift', '~> 1.7.5'
  pod 'FacebookCore'
  pod 'FBSDKLoginKit'
  pod 'AWSS3'
  pod 'IQKeyboardManagerSwift'
  pod ‘TwitterKit’, ‘~> 3.0'
  pod 'SideMenu'

  target 'WizcardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WizcardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
